branch-defaults:
  default:
    environment: django-env
    group_suffix: null
environment-defaults:
  Knowledgebase-dev:
    branch: null
    repository: null
global:
  application_name: kb_app
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: eu-north-1
  include_git_submodules: true
  instance_profile: null
  no-verify-ssl: true
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: null
  workspace_type: Application
