# Generated by Django 4.2.4 on 2023-08-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='kbentry',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='kbentry',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
