# Generated by Django 4.2.4 on 2023-08-16 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kb_app', '0003_alter_audit_kb_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kbentry',
            name='modified_datetime',
        ),
    ]
